[package]
name = "rgis-ui"
version = "0.1.0"
authors = ["Corey Farwell <coreyf@rwell.org>"]
edition = "2021"
publish = false

[dependencies]
async-channel = "1"
bevy = { version = "0.6", default-features = false, features = [
    "bevy_winit",
    "bevy_core_pipeline",
#"bevy_pbr",
#"bevy_gltf",
"bevy_render",
"bevy_sprite",
#"bevy_text",
"bevy_ui",
] }
bevy_egui = "0.11"
rfd = "0.8"
rgis-layer-id = { path = "../rgis-layer-id" }
rgis-layers = { path = "../rgis-layers" }
rgis-library = { path = "../rgis-library" }
rgis-events = { path = "../rgis-events" }
rgis-mouse = { path = "../rgis-mouse" }
rgis-settings = { path = "../rgis-settings" }
webbrowser = "0.6"
