[package]
name = "rgis-ui"
version = "0.1.0"
authors = ["Corey Farwell <coreyf@rwell.org>"]
edition = "2021"
publish = false

[dependencies]
bevy = { version = "0.8", default-features = false, features = [
    "bevy_winit",
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_sprite",
    "bevy_ui",
    "wayland",
] }
bevy_egui = "0.16"
geo-features = { path = "../geo-features" }
rfd = "0.10"
rgis-layer-id = { path = "../rgis-layer-id" }
rgis-layers = { path = "../rgis-layers" }
rgis-library = { path = "../rgis-library" }
rgis-events = { path = "../rgis-events" }
rgis-mouse = { path = "../rgis-mouse" }
rgis-settings = { path = "../rgis-settings" }
bevy-jobs = { path = "../bevy-jobs" }
webbrowser = "0.7"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
geo = { version = "0.23", features = ["use-proj"] }
