[package]
name = "geo-file-loader"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bytes = "1"
time-logger = { path = "../time-logger" }
geo = "0.29"
geo-features = { path = "../geo-features" }
geozero = { version = "0.14", features = ["with-wkt", "with-gpx", "with-shp"] }
thiserror = "2"
geo-projected = { path = "../geo-projected" }
typed-num = { path = "../typed-num" }
