[package]
name = "bevy-web-resizing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "*"
bevy = "0.6"
winit = "*"
wasm-bindgen = "*"
web-sys = "*"
