[package]
name = "rgis-layers"
version = "0.1.0"
authors = ["Corey Farwell <coreyf@rwell.org>"]
edition = "2021"
publish = false

[dependencies]
bevy = { version = "0.9", default-features = false, features = [
    "bevy_winit",
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_sprite",
    "bevy_ui",
    "wayland",
    "png",
] }
colorous = "1"
geo-features = { path = "../geo-features" }
geo-geom-type = { path = "../geo-geom-type" }
geo-projected = { path = "../geo-projected" }
rgis-events = { path = "../rgis-events" }
rgis-layer-id = { path = "../rgis-layer-id" }
thiserror = "1"
serde_json = "1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
geo = { version = "0.24", features = ["use-proj"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
geo = "0.24"
